level = [
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "W            W                                   W",
    "W            W                                   W",
    "W                                                W",
    "W            W          W                        W",
    "W                       W                        W",
    "W                       W                        W",
    "W                       W                        W",
    "W                       W                        W",
    "W                       W        W               W",
    "W                       W        W               W",
    "W                       W        W               W",
    "W    WWW                W                        W",
    "W                       W                        W",
    "W                       W                        W",
    "W                               WWWW             W",
    "W                       W                        W",
    "W  WW                   W                        W",
    "W                                                W",
    "W                                                W",
    "W                                                W",
    "W                                                W",
    "W                                                W",
    "W                                      WWWW      W",
    "W                W                       WW      W",
    "W                W                        W      W",
    "W               W                                W",
    "W               W    E   W                       W",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
]